/*
 * About.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

/**
 *
 * @author  __USER__
 */
public class About extends javax.swing.JFrame {

	/** Creates new form About */
	public About() {
		initComponents();
		this.setLocation(500, 200);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u5173\u4e8e\u6211\u4eec");

		jLabel3.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel3.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\writer.png")); // NOI18N
		jLabel3.setText("\u4f5c\u8005\uff1a@\u83ab\u5189");

		jLabel4.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel4.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\tencent_QQ.png")); // NOI18N
		jLabel4.setText("\u8054\u7cfb\u65b9\u5f0f\uff1a@230850****");

		jLabel5.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel5.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\calendar_dates.png")); // NOI18N
		jLabel5.setText("\u521b\u4f5c\u65e5\u671f\uff1a@2019/06/30");

		jLabel6.setFont(new java.awt.Font("宋体", 1, 36));
		jLabel6.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\about_1.png")); // NOI18N

		jLabel1.setFont(new java.awt.Font("宋体", 1, 48));
		jLabel1.setText("\u5173\u4e8e\u6211\u4eec");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(85, 85,
																		85)
																.addComponent(
																		jLabel6)
																.addGap(70, 70,
																		70)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						271,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						246,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel5)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(257,
																		257,
																		257)
																.addComponent(
																		jLabel1)))
								.addContainerGap(248, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(93, 93, 93)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										85, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel3)
																.addGap(44, 44,
																		44)
																.addComponent(
																		jLabel4)
																.addGap(50, 50,
																		50)
																.addComponent(
																		jLabel5)))
								.addGap(60, 60, 60)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new About().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	// End of variables declaration//GEN-END:variables

}