/*
 * AddJourneyFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.sql.Connection;

import javax.swing.JOptionPane;

import com.DataBase.Journey_db;
import com.Model.Journey;
import com.Util.Tools;

/**
 *
 * @author  __USER__
 */
public class AddJourneyFrm extends javax.swing.JInternalFrame {

	/** Creates new form AddJourneyFrm */
	public AddJourneyFrm() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtjourneyname = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		txtjourneyyear = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txtjourneygrade = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtjourneyplan = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txtjourneymoney = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtdetails = new javax.swing.JTextArea();
		btnok = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\name_48px.png")); // NOI18N
		jLabel1.setText("\u540d\u79f0\uff1a");

		jLabel2.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\calendar_dates.png")); // NOI18N
		jLabel2.setText("\u6210\u7acb\u65f6\u95f4\uff1a");

		txtjourneyyear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				txtjourneyyearActionPerformed(evt);
			}
		});

		jLabel3.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\stars48.png")); // NOI18N
		jLabel3.setText("\u63a8\u8350\u7b49\u7ea7\uff1a");

		jLabel4.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\plan48.png")); // NOI18N
		jLabel4.setText("\u51fa\u884c\u8ba1\u5212\uff1a");

		jLabel5.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\money_48px.png")); // NOI18N
		jLabel5.setText("\u51fa\u884c\u8d39\u7528\uff1a");

		jLabel6.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\thumbsup48.png")); // NOI18N
		jLabel6.setText("\u8be6\u60c5\uff1a");

		txtdetails.setColumns(20);
		txtdetails.setRows(5);
		jScrollPane1.setViewportView(txtdetails);

		btnok.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\add.png")); // NOI18N
		btnok.setText("\u786e\u5b9a");
		btnok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnokActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(85, 85, 85)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addGap(39, 39,
																		39)
																.addComponent(
																		txtjourneyname,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		234,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						jLabel6))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jScrollPane1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										238,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						txtjourneymoney,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						238,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtjourneygrade,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						238,
																						Short.MAX_VALUE))))
								.addGap(70, 70, 70)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(jLabel4))
								.addGap(47, 47, 47)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						txtjourneyyear,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						175,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						txtjourneyplan,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						175,
																						Short.MAX_VALUE))
																.addGap(161,
																		161,
																		161))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		btnok,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		140,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addContainerGap()))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(52, 52, 52)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtjourneyyear,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2)
												.addComponent(
														txtjourneyname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(59, 59, 59)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														txtjourneyplan,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtjourneygrade,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(46, 46,
																		46)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						txtjourneymoney,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(53, 53,
																		53)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel6)
																				.addComponent(
																						jScrollPane1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(147,
																		147,
																		147)
																.addComponent(
																		btnok,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		40,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(105, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void btnokActionPerformed(java.awt.event.ActionEvent evt) {
		String journeyname = txtjourneyname.getText();
		String journeyyear = txtjourneyyear.getText();
		String journeyplan = txtjourneyplan.getText();
		String journeygrade = txtjourneygrade.getText();
		String journeydetails = txtdetails.getText();
		String journeymoney = txtjourneymoney.getText();
		if (journeyplan.equals("")) {
			journeymoney = "";
			JOptionPane.showMessageDialog(null, "没有出行计划，你的出行费用已被重置为0");
		}
		Journey journey = new Journey(journeyname, journeyyear, journeygrade,
				journeyplan, journeydetails, journeymoney);
		Tools t = new Tools();
		Journey_db journey_db = new Journey_db();
		Connection con = null;
		try {
			con = t.getConn();
			int n = journey_db.Add_Journey_Info(con, journey);
			if (n > 0) {
				JOptionPane.showMessageDialog(null, "添加成功！");
				resetValue();
			} else {
				JOptionPane.showMessageDialog(null, "添加失败！");
				resetValue();
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			t.closeConn(con);
		}
	}

	/**
	 * 重置表单
	 */
	public void resetValue() {
		txtjourneyname.setText("");
		txtjourneyyear.setText("");
		txtjourneymoney.setText("");
		txtjourneygrade.setText("");
		txtdetails.setText("");
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnok;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea txtdetails;
	private javax.swing.JTextField txtjourneygrade;
	private javax.swing.JTextField txtjourneymoney;
	private javax.swing.JTextField txtjourneyname;
	private javax.swing.JTextField txtjourneyplan;
	private javax.swing.JTextField txtjourneyyear;
	// End of variables declaration//GEN-END:variables

}