/*
 * JourneyManageFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.awt.event.ActionEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.DataBase.Journey_db;
import com.Model.Journey;
import com.Util.Tools;

/**
 * 
 * @author __USER__
 */
public class JourneyManageFrm extends javax.swing.JInternalFrame {

	/** Creates new form JourneyManageFrm */
	public JourneyManageFrm() {
		initComponents();
		filltable(new Journey());
		this.setLocation(300, 150);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtjourneymanage = new javax.swing.JTextField();
		btnsearch = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jnmanagetable = new javax.swing.JTable();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		txtJn_name = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txtJn_year = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtJn_grade = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txtJn_plan = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		txtJn_details = new javax.swing.JTextArea();
		jLabel7 = new javax.swing.JLabel();
		txtmoney = new javax.swing.JTextField();
		btnupdate = new javax.swing.JButton();
		btndalete = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u65c5\u884c\u793e\u7ba1\u7406");
		addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				formMouseClicked(evt);
			}
		});

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\travel.png")); // NOI18N
		jLabel1.setText("\u65c5\u884c\u793e\uff1a");

		txtjourneymanage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
//				txtjourneymanageActionPerformed(evt);
			}
		});

		btnsearch
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\sear.png")); // NOI18N
		btnsearch.setText("\u67e5\u8a62");
		btnsearch.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnsearchActionPerformed(evt);
			}
		});

		jnmanagetable.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null } }, new String[] {
						"名稱", "成立時間", "推薦等級", "出行計劃", "出行费用", "詳細描述" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false,
					false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jnmanagetable.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jnmanagetableMousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jnmanagetable);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 551,
								Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 157,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(38, Short.MAX_VALUE)));

		jLabel2.setText("\u540d\u7a31\uff1a");

		txtJn_name.setEditable(false);

		jLabel3.setText("\u6210\u7acb\u6642\u9593\uff1a");

		jLabel4.setText("\u63a8\u85a6\u7b49\u7d1a:");

		jLabel5.setText("\u8fd1\u671f\u51fa\u884c\u8a08\u5283:");

		jLabel6.setText("\u8a73\u7d30\u63cf\u8ff0:");

		txtJn_details.setColumns(20);
		txtJn_details.setRows(5);
		jScrollPane2.setViewportView(txtJn_details);

		jLabel7.setText("\u51fa\u884c\u8d39\u7528\uff1a");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				432,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel5)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												txtJn_plan))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								jPanel2Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel2)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												txtJn_name,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												104,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												jLabel3)))
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												txtJn_year,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												93,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel4)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												txtJn_grade,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												85,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel2Layout
																										.createSequentialGroup()
																										.addGap(36,
																												36,
																												36)
																										.addComponent(
																												jLabel7)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												txtmoney,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												141,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addContainerGap(28, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																txtJn_name,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3)
														.addComponent(
																txtJn_year,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addComponent(
																txtJn_grade,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(31, 31, 31)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																txtJn_plan,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(
																txtmoney,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel6)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(17, Short.MAX_VALUE)));

		btnupdate
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\26154.png")); // NOI18N
		btnupdate.setText("\u4fee\u6539");
		btnupdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnupdateActionPerformed(evt);
			}
		});

		btndalete
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\error_2.png")); // NOI18N
		btndalete.setText("\u522a\u9664");
		btndalete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btndaleteActionPerformed(evt);
			}
		});

		jButton1.setText("\u67e5\u770b\u8be6\u60c5");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup()
																.addGap(73, 73,
																		73)
																.addComponent(
																		jPanel2,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(61, 61,
																		61)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jPanel1,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel1)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										txtjourneymanage,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										236,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(30,
																										30,
																										30)
																								.addComponent(
																										btnsearch)))))
								.addGap(185, 185, 185))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(171, 171, 171)
								.addComponent(btnupdate,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										98,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(29, 29, 29).addComponent(jButton1)
								.addGap(28, 28, 28).addComponent(btndalete)
								.addContainerGap(302, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(88, 88, 88)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtjourneymanage,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														36,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														btnsearch,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														39,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(50, 50, 50)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnupdate)
												.addComponent(btndalete)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														31,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(27, 27, 27)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 查看详情
	 * @param evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		int n = JOptionPane.showConfirmDialog(null, "即将跳转,是否？");
		if (n == 0) {
			int row = jnmanagetable.getSelectedRow();
			try {
				Runtime.getRuntime().exec(
						"cmd /c start https://www.baidu.com/s?wd="
								+ (String) jnmanagetable.getValueAt(row, 0)
								+ "");
			} catch (IOException ee) {
				ee.printStackTrace();
			}
		} else if (n == 1) {
			JOptionPane.showMessageDialog(null, "真遗憾呢");
		} else {

		}
	}

	private void formMouseClicked(java.awt.event.MouseEvent evt) {
		this.toFront();// 置于顶层
	}

	/**
	 * 删除旅行社
	 * 
	 * @param evt
	 */
	private void btndaleteActionPerformed(java.awt.event.ActionEvent evt) {
		String Jn_name = this.txtJn_name.getText();
		Tools t = new Tools();
		Journey_db journey = new Journey_db();
		if (t.isEmpty(Jn_name)) {
			JOptionPane.showMessageDialog(null, "请选择你要删除的旅行社");
		} else {
			Connection con = t.getConn();
			int n = journey.deljourney(con, Jn_name);
			if (n > 0) {
				JOptionPane.showMessageDialog(null, "删除成功!");
				resetValue();
				filltable(new Journey());
			} else {
				JOptionPane.showMessageDialog(null, "删除失败！");
			}

		}
	}

	/**
	 * 修改事件处理
	 * 
	 * @param evt
	 */
	private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {
		String Jn_year = this.txtJn_year.getText();
		String Jn_grade = this.txtJn_grade.getText();
		String Jn_details = this.txtJn_details.getText();
		String Jn_name = this.txtJn_name.getText();
		String Jn_plan = this.txtJn_plan.getText();
		String Jn_money = this.txtmoney.getText();
		if (Jn_plan.equals("")) {
			JOptionPane.showMessageDialog(null, "该旅行社目前没有出行计划，不能要钱");
			Jn_money = "";
		}
		Journey journey = new Journey();
		journey.setJn_details(Jn_details);
		journey.setJn_grade(Jn_grade);
		journey.setJn_name(Jn_name);
		journey.setJn_year(Jn_year);
		journey.setJn_plan(Jn_plan);
		journey.setJn_money(Jn_money);
		Connection con = null;
		Journey_db journey_db = new Journey_db();
		Tools t = new Tools();
		if (t.isEmpty(Jn_name)) {
			JOptionPane.showMessageDialog(null, "请选择你要修改的旅行社");
		} else {
			try {
				con = t.getConn();
				int n = journey_db.updateJourney(con, journey);
				if (n > 0) {
					JOptionPane.showMessageDialog(null, "修改成功！");
					resetValue();
					filltable(new Journey());

				} else {
					JOptionPane.showMessageDialog(null, "修改失败！");
				}
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
				t.closeConn(con);
			}
		}
	}

	/**
	 * 鼠标选中行事件处理
	 * 
	 * @param evt
	 */
	private void jnmanagetableMousePressed(java.awt.event.MouseEvent evt) {

		int row = jnmanagetable.getSelectedRow();
		txtJn_name.setText((String) jnmanagetable.getValueAt(row, 0));
		txtJn_details.setText((String) jnmanagetable.getValueAt(row, 5));
		txtJn_grade.setText((String) jnmanagetable.getValueAt(row, 2));
		txtJn_plan.setText((String) jnmanagetable.getValueAt(row, 3));
		txtJn_year.setText((String) jnmanagetable.getValueAt(row, 1));
		txtmoney.setText((String) jnmanagetable.getValueAt(row, 4));

	}

	// GEN-END:initComponents

	/**
	 * 查询事件处理
	 * 
	 * @param evt
	 */
	private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {
		String Jn_name = this.txtjourneymanage.getText();
		Tools t = new Tools();
		// if (t.isEmpty(Jn_name)) {
		// JOptionPane.showMessageDialog(null, "请输入你要查找的旅行社");
		// } else {
		Journey journey = new Journey();
		journey.setJn_name(Jn_name);
		this.filltable(journey);
		// }
	}

	// private void txtjourneymanageActionPerformed(java.awt.event.ActionEvent
	// evt) {
	// // TODO add your handling code here:
	// }

	/**
	 * 清空文本框
	 */
	public void resetValue() {
		txtJn_name.setText("");
		txtJn_details.setText("");
		txtJn_grade.setText("");
		txtJn_plan.setText("");
		txtJn_year.setText("");
		txtmoney.setText("");

	}

	/**
	 * 初始化旅行社的表格
	 * 
	 * @param journey
	 */
	private void filltable(Journey journey) {
		DefaultTableModel dtm = (DefaultTableModel) jnmanagetable.getModel();
		dtm.setRowCount(0);// 清空表格
		Connection con = null;
		Tools t = new Tools();
		try {
			con = t.getConn();
			Journey_db journey_db = new Journey_db();
			// System.out.println("？？？");
			ResultSet rs = journey_db.list(con, journey);
			while (rs.next()) {
				// System.out.println("filltable裏面的這裏呢");
				Vector v = new Vector();
				v.add(rs.getString("Jn_name"));
				v.add(rs.getString("Jn_year"));
				v.add(rs.getString("Jn_grade"));
				v.add(rs.getString("Jn_plan"));
				v.add(rs.getString("Jn_money"));
				v.add(rs.getString("Jn_details"));
				dtm.addRow(v);
				// System.out.println("fill table裏面的這裏呢");
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			t.closeConn(con);
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btndalete;
	private javax.swing.JButton btnsearch;
	private javax.swing.JButton btnupdate;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTable jnmanagetable;
	private javax.swing.JTextArea txtJn_details;
	private javax.swing.JTextField txtJn_grade;
	private javax.swing.JTextField txtJn_name;
	private javax.swing.JTextField txtJn_plan;
	private javax.swing.JTextField txtJn_year;
	private javax.swing.JTextField txtjourneymanage;
	private javax.swing.JTextField txtmoney;
	// End of variables declaration//GEN-END:variables

}