/*
 * Logfrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.sql.Connection;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.Model.User;
import com.Util.Tools;
import com.Util.ValidCode;

/**
 * 
 * @author __USER__
 */
public class Logfrm extends javax.swing.JFrame {

	/** Creates new form Logfrm */
	public Logfrm() {

		initComponents();
		this.setLocation(500, 200);

		/**
		 * 
		 * 初始化登录窗体背景
		 */

		// 加载图片
		ImageIcon icon = new ImageIcon("images/4.jpg");
		// 将图片放入label中
		JLabel label = new JLabel(icon);
		// 设置label的大小
		label.setBounds(0, 0, icon.getIconWidth(), icon.getIconHeight());
		// 获取窗口的第二层，将label放入
		this.getLayeredPane().add(label, new Integer(Integer.MIN_VALUE));
		// 获取frame的顶层容器,并设置为透明
		Container cp;
		cp = this.getContentPane();
		((JPanel) cp).setOpaque(false);
		cp.setLayout(new BorderLayout());

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		textField1 = new java.awt.TextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jButton3 = new javax.swing.JButton();
		btnReset = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jtf_code = new javax.swing.JTextField();
		validcode = new com.Util.ValidCode();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7528\u6237\u767b\u5f55");

		textField1.setFont(new java.awt.Font("Dialog", 1, 24));
		textField1.setName("txtname");

		jButton3.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\guanliyuan.png")); // NOI18N
		jButton3.setText("\u7ba1\u7406\u5458\u767b\u5f55");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		btnReset.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\reset.png")); // NOI18N
		btnReset.setText("\u91cd\u7f6e");
		btnReset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnResetActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("宋体", 1, 36));
		jLabel1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\System.png")); // NOI18N
		jLabel1.setText("\u65c5\u6e38\u7ba1\u7406\u7cfb\u7edf");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\user_.png")); // NOI18N
		jLabel2.setText("\u7528\u6237\u540d\uff1a");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel3.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\see_no_48px.png")); // NOI18N
		jLabel3.setText("\u5bc6 \u7801\uff1a");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel4.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\yanzhen_48px.png")); // NOI18N
		jLabel4.setText("\u9a8c\u8bc1\u7801\uff1a");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(59, 59, 59)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addComponent(jLabel3)
												.addComponent(jLabel4))
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jtf_code,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		167,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(61, 61,
																		61)
																.addComponent(
																		validcode,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		163,
																		Short.MAX_VALUE))
												.addComponent(
														jPasswordField1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														391, Short.MAX_VALUE)
												.addComponent(
														textField1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														391, Short.MAX_VALUE)
												.addComponent(jLabel1)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton3)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		121,
																		Short.MAX_VALUE)
																.addComponent(
																		btnReset,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		135,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(121, 121, 121)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(15, 15, 15)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel2)
												.addComponent(
														textField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														35,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(32, 32, 32)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														jPasswordField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														32,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(43, 43, 43)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						validcode,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						35,
																						Short.MAX_VALUE)
																				.addComponent(
																						jtf_code,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						35,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(42,
																										42,
																										42)
																								.addComponent(
																										btnReset))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(50,
																										50,
																										50)
																								.addComponent(
																										jButton3)))))
								.addGap(29, 29, 29)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {

		Reset();
	}

	/**
	 * 重置文本框
	 */
	private void Reset() {
		// TODO Auto-generated method stub
		textField1.setText("");
		this.jPasswordField1.setText("");
		jtf_code.setText("");
	}

	/**
	 * 管理员登录
	 * 
	 * @param evt
	 */
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		jButton3.setIcon(new ImageIcon("images/btn1.jpg"));
		Tools t = new Tools();
		String username = textField1.getText();
		String pw = new String(this.jPasswordField1.getPassword());

		if (t.isEmpty(username) || t.isEmpty(pw)) {
			JOptionPane.showMessageDialog(null, "用户名或密码不能为空");
		} else {
			Connection conn = t.getConn();
			User user = t.login(conn, username, pw);
			// /**
			// * 这个user用来PersonInfoFrm界面里获取当前登录者的信息
			// */
			// PersonInfoFrm p = new PersonInfoFrm();
			// p.TransUser(user);

			if (user != null) {
				
				if (!isValidCodeRight()) {
					JOptionPane.showMessageDialog(null, "验证码错误！");
				}
				if (isValidCodeRight()) {
					JOptionPane.showMessageDialog(null, "登录成功！");
					dispose();
					main_Frm main = new main_Frm();
					// main.tansUser(user);
					main.setVisible(true);
				} else {
					JOptionPane.showMessageDialog(null, "登录失败！");
				}
			}

		}

	}

	/**
	 * 这下面用来实现验证码功能
	 */
	/**
	 * 
	 * 设置按钮风格：透明
	 * 
	 * 
	 * 
	 * @param btn
	 */

	private ValidCode vcode;

	private void setJButton(JButton btn) {

		btn.setBackground(new Color(102, 0, 204));// 紫色

		btn.setFont(new Font("Dialog", Font.BOLD, 24));

		btn.setOpaque(false);

		btn.setBorder(BorderFactory.createEmptyBorder());

	}

	/**
	 * 
	 * 验证码的校验
	 * 
	 * 
	 * 
	 * @return
	 */

	public boolean isValidCodeRight() {

		if (jtf_code == null) {

			return false;

		}

		if (validcode == null) {

			return true;

		}

		if (validcode.getCode().equals(jtf_code.getText())) {

			return true;

		}

		return false;

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Logfrm().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnReset;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jtf_code;
	private java.awt.TextField textField1;
	private ValidCode validcode;
	// End of variables declaration//GEN-END:variables

}