/*
 * main_Frm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.awt.event.ActionEvent;

import javax.swing.JOptionPane;

import com.DataBase.Journey_db;
import com.Model.User;
import com.Util.Tools;

/**
 * 
 * @author __USER__
 */
public class main_Frm extends javax.swing.JFrame {

	Tools t = null;
	User user = null;
	Journey_db journey_db = null;

	/** Creates new form main_Frm */
	public main_Frm() {
		initComponents();
		this.setLocation(500, 200);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		Jn_Info_Item = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JSeparator();
		SceneItems = new javax.swing.JMenuItem();
		jSeparator5 = new javax.swing.JSeparator();
		User_Manage_Item = new javax.swing.JMenuItem();
		jSeparator2 = new javax.swing.JSeparator();
		user_info_Item = new javax.swing.JMenuItem();
		jSeparator4 = new javax.swing.JSeparator();
		searchItem = new javax.swing.JMenuItem();
		jSeparator3 = new javax.swing.JSeparator();
		exitMenuItem = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		add_Scene_Item = new javax.swing.JMenuItem();
		jSeparator6 = new javax.swing.JSeparator();
		add_Journey_Item = new javax.swing.JMenuItem();
		jSeparator7 = new javax.swing.JSeparator();
		add_User_Item = new javax.swing.JMenuItem();
		helpMenu = new javax.swing.JMenu();
		aboutMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u4e3b\u9875\u9762");

		fileMenu.setText("\u7ba1\u7406");

		Jn_Info_Item
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\business.png")); // NOI18N
		Jn_Info_Item.setText("\u65c5\u884c\u793e\u4fe1\u606f\u7ba1\u7406");
		Jn_Info_Item.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				Jn_Info_ItemMouseClicked(evt);
			}
		});
		Jn_Info_Item.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				Jn_Info_ItemActionPerformed(evt);
			}
		});
		fileMenu.add(Jn_Info_Item);
		fileMenu.add(jSeparator1);

		SceneItems
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\18px.png")); // NOI18N
		SceneItems.setText("\u666f\u70b9\u4fe1\u606f\u7ba1\u7406");
		SceneItems.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				SceneItemsActionPerformed(evt);
			}
		});
		fileMenu.add(SceneItems);
		fileMenu.add(jSeparator5);

		User_Manage_Item
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\Explorer.png")); // NOI18N
		User_Manage_Item.setText("\u7528\u6237\u4fe1\u606f\u7ba1\u7406");
		User_Manage_Item.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				User_Manage_ItemActionPerformed(evt);
			}
		});
		fileMenu.add(User_Manage_Item);
		fileMenu.add(jSeparator2);

		user_info_Item
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\info.png")); // NOI18N
		user_info_Item.setText("\u4e2a\u4eba\u4fe1\u606f");
		user_info_Item.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				user_info_ItemActionPerformed(evt);
			}
		});
		fileMenu.add(user_info_Item);
		fileMenu.add(jSeparator4);

		searchItem
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\search_16p.png")); // NOI18N
		searchItem.setText("\u67e5\u8a62");
		searchItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchItemActionPerformed(evt);
			}
		});
		fileMenu.add(searchItem);
		fileMenu.add(jSeparator3);

		exitMenuItem
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\exit.png")); // NOI18N
		exitMenuItem.setText("\u9000\u51fa");
		exitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				exitMenuItemMouseClicked(evt);
			}
		});
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}

			private void exitMenuItemActionPerformed(ActionEvent evt) {
				// TODO Auto-generated method stub
				int n=JOptionPane.showConfirmDialog(null, "确认退出?");
				if(n==0){
					System.exit(0);
				}
			}
		});
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		jMenu1.setText("\u6dfb\u52a0");

		add_Scene_Item
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\add_16px.png")); // NOI18N
		add_Scene_Item.setText("\u6dfb\u52a0\u666f\u70b9");
		add_Scene_Item.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				add_Scene_ItemActionPerformed(evt);
			}
		});
		jMenu1.add(add_Scene_Item);
		jMenu1.add(jSeparator6);

		add_Journey_Item
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\add_16px.png")); // NOI18N
		add_Journey_Item.setText("\u6dfb\u52a0\u65c5\u884c\u793e");
		add_Journey_Item.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				add_Journey_ItemActionPerformed(evt);
			}
		});
		jMenu1.add(add_Journey_Item);
		jMenu1.add(jSeparator7);

		add_User_Item
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\add_16px.png")); // NOI18N
		add_User_Item.setText("\u6dfb\u52a0\u7528\u6237");
		add_User_Item.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				add_User_ItemActionPerformed(evt);
			}
		});
		jMenu1.add(add_User_Item);

		menuBar.add(jMenu1);

		helpMenu.setText("\u5e2e\u52a9");

		aboutMenuItem
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\about_16px.png")); // NOI18N
		aboutMenuItem.setText("\u5173\u4e8e\u6211\u4eec");
		aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				aboutMenuItemActionPerformed(evt);
			}
		});
		helpMenu.add(aboutMenuItem);

		menuBar.add(helpMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 1024,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 561,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 主界面个人信息管理
	 * @param evt
	 */
	private void user_info_ItemActionPerformed(java.awt.event.ActionEvent evt) {
		PersonInfoFrm personinfofrm=new PersonInfoFrm();
		personinfofrm.setVisible(true);
	}

	/**
	 * 跳转到用户添加页面实现用户添加功能
	 * @param evt
	 */
	private void add_User_ItemActionPerformed(java.awt.event.ActionEvent evt) {
		AddUserInfoFrm adduser = new AddUserInfoFrm();
		adduser.setVisible(true);
		this.add(adduser);
	}

	/**
	 * 跳转至添加旅行社界面
	 * @param evt
	 */
	private void add_Journey_ItemActionPerformed(java.awt.event.ActionEvent evt) {
		AddJourneyFrm addjourneyfrm = new AddJourneyFrm();
		addjourneyfrm.setVisible(true);
		this.add(addjourneyfrm);
	}

	private void add_Scene_ItemActionPerformed(java.awt.event.ActionEvent evt) {
		Add_Scene add_scene = new Add_Scene();
		add_scene.setVisible(true);
		this.add(add_scene);
	}

	private void User_Manage_ItemActionPerformed(java.awt.event.ActionEvent evt) {
		UserinfoManageFrm userinfomanagefrm = new UserinfoManageFrm();
		userinfomanagefrm.setVisible(true);
		this.add(userinfomanagefrm);
	}

	private void SceneItemsActionPerformed(java.awt.event.ActionEvent evt) {
		SceneManageFrm scenemanagefrm = new SceneManageFrm();
		scenemanagefrm.setVisible(true);
		this.add(scenemanagefrm);
	}

	private void searchItemActionPerformed(java.awt.event.ActionEvent evt) {
		Search s = new Search();
		s.setVisible(true);
		this.add(s);
	}

	private void exitMenuItemMouseClicked(java.awt.event.MouseEvent evt) {

		System.exit(0);
	}

	private void Jn_Info_ItemActionPerformed(java.awt.event.ActionEvent evt) {
		JourneyManageFrm jour = new JourneyManageFrm();
		jour.setVisible(true);
		//		this.dispose();
		this.add(jour);
	}

	private void Jn_Info_ItemMouseClicked(java.awt.event.MouseEvent evt) {
		JourneyManageFrm jour = new JourneyManageFrm();
		jour.setVisible(true);
		this.add(jour);
	}
	
	/**
	 * 登录页面传到个人信息页面的中间站
	 * @param user
	 * @return
	 */
//	public User tansUser(User user){
//		PersonInfoFrm p=new PersonInfoFrm();
//		p.TransUser(user);
//		return user;
//	}
	
	
	

	/**
	 * 查找旅行社的事件处理
	 * 
	 * @param evt
	 */
	//	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	//		String searchText = txtSearch.getText();
	//		t = new Tools();
	//		if (t.isEmpty(searchText)) {
	//			JOptionPane.showMessageDialog(null, "输入你要查找的旅行社名称");
	//		} else {
	//			Journey journey = new Journey();
	//			Connection con = t.getConn();
	//			journey = journey_db.search_journey(con, searchText);
	//			// 返回了一个旅行社对象，要在旅行社的界面显示出来
	//		}
	//	}

	private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
		About about = new About();
		about.setVisible(true);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new main_Frm().setVisible(true);
			}
		});
	}

	//
	//	 private void timer1_Tick(Object sender, Event e)
	//	 {
	//	 //实现滚动显示“天行健，君子以自强不息!”
	//	 if (jLabel4.LEFT >= this.WIDTH)
	//	 {
	//	 jLabel4.LEFT = 0;
	//	 }
	//	 jLabel4.LEFT += 1;
	//	 }

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JMenuItem Jn_Info_Item;
	private javax.swing.JMenuItem SceneItems;
	private javax.swing.JMenuItem User_Manage_Item;
	private javax.swing.JMenuItem aboutMenuItem;
	private javax.swing.JMenuItem add_Journey_Item;
	private javax.swing.JMenuItem add_Scene_Item;
	private javax.swing.JMenuItem add_User_Item;
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JSeparator jSeparator6;
	private javax.swing.JSeparator jSeparator7;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem searchItem;
	private javax.swing.JMenuItem user_info_Item;
	// End of variables declaration//GEN-END:variables

}