/*
 * PersonInfoFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.Connection;
import java.sql.ResultSet;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

import com.DataBase.Friend_db;
import com.DataBase.Journey_db;
import com.DataBase.Scene_db;
import com.Model.Journey;
import com.Model.Scene;
import com.Model.User;
import com.Util.Tools;

/**
 * 
 * @author __USER__
 */
public class PersonInfoFrm extends javax.swing.JFrame {

	Tools t = new Tools();
	Journey_db journey_db = new Journey_db();
	Scene_db scene_db = new Scene_db();

	/** Creates new form PersonInfoFrm */
	public PersonInfoFrm() {
		initComponents();
		this.setLocation(350, 150);
		//加载图片
		ImageIcon icon = new ImageIcon("images/4.jpg");
		//将图片放入label中
		JLabel label = new JLabel(icon);
		//设置label的大小
		label.setBounds(0, 0, icon.getIconWidth(), icon.getIconHeight());
		//获取窗口的第二层，将label放入
		this.getLayeredPane().add(label, new Integer(Integer.MIN_VALUE));
		//获取frame的顶层容器,并设置为透明
		Container cp;
		cp = this.getContentPane();
		((JPanel) cp).setOpaque(false);
		cp.setLayout(new BorderLayout());
		fillMyfriend();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jLabel1 = new javax.swing.JLabel();
jLabel4 = new javax.swing.JLabel();
jLabel5 = new javax.swing.JLabel();
jcbplan = new javax.swing.JComboBox();
jButton1 = new javax.swing.JButton();
jScrollPane1 = new javax.swing.JScrollPane();
txtarea = new javax.swing.JTextArea();
jcbfriend = new javax.swing.JComboBox();

setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48));
jLabel1.setIcon(new javax.swing.ImageIcon("E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\idcard128px.png")); // NOI18N
jLabel1.setText("\u6211\u7684\u4e2a\u4eba\u4fe1\u606f");

jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
jLabel4.setText("\u6211\u7684\u597d\u53cb\uff1a");

jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
jLabel5.setText("\u6211\u7684\u884c\u7a0b\uff1a");

jcbplan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "请选择...", "景点行程", "旅行社行程" }));
jcbplan.addItemListener(new java.awt.event.ItemListener() {
public void itemStateChanged(java.awt.event.ItemEvent evt) {
jcbplanItemStateChanged(evt);
}
});

jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
jButton1.setIcon(new javax.swing.ImageIcon("E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\confirm_48px.png")); // NOI18N
jButton1.setText("\u7ba1\u7406\u6211\u7684\u4fe1\u606f");
jButton1.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
jButton1ActionPerformed(evt);
}
});

txtarea.setColumns(20);
txtarea.setEditable(false);
txtarea.setFont(new java.awt.Font("Monospaced", 0, 18));
txtarea.setRows(5);
jScrollPane1.setViewportView(txtarea);

//jcbfriend.setModel(javax.swing.DefaultComboBoxModel@5e23d4e6);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGap(96, 96, 96)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
.addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
.addGap(34, 34, 34)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jcbfriend, 0, 221, Short.MAX_VALUE)
.addComponent(jcbplan, 0, 221, Short.MAX_VALUE))
.addGap(39, 39, 39)
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
.addComponent(jLabel1))
.addGap(144, 144, 144))
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addContainerGap()
.addComponent(jLabel1)
.addGap(42, 42, 42)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addGroup(layout.createSequentialGroup()
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel5)
.addComponent(jcbplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(75, 75, 75)
.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
.addComponent(jLabel4)
.addComponent(jcbfriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
.addGap(40, 40, 40)
.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
.addContainerGap(86, Short.MAX_VALUE))
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		ManageInfo manageInfo = new ManageInfo();
		manageInfo.setVisible(true);
		//		this.dispose();
	}

	/**
	 * 获取登录界面的登陆者的信息显示
	 */
	//	public void TransUser(User user){
	//		System.out.println(user.getName());
	//		System.out.println(user.getSex());
	//		this.txtname.setText(user.getName());
	//		this.txtsex.setText(user.getSex());
	//	}

	/**
	 * 初始化我的好友下拉框
	 */
	public void fillMyfriend() {
		Connection con = null;
		try {
			con = t.getConn();
			ResultSet rs = Friend_db.SearchMyFriend(con);
			while (rs.next()) {
				User user = new User();
				user.setHome(rs.getString("home"));
				user.setName(rs.getString("name"));
				this.jcbfriend.addItem(user);
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			t.closeConn(con);
		}

	}

	/**
	 * 下拉菜单值变化事件处理
	 * @param evt
	 */
	private void jcbplanItemStateChanged(java.awt.event.ItemEvent evt) {
		switch (jcbplan.getSelectedIndex()) {
		case 0:
			txtarea.setText("");
			break;
		case 1:
			txtarea.setText("");
			Scene scene = Search_Scene_Plan();
			//			txtarea.setText(scene.getScene_name());
			break;
		case 2:
			txtarea.setText("");
			Journey journey = Search_Journey_plan();
			//			System.out.println(journey.getJn_plan());
			txtarea.setText(journey.getJn_name() + "  目标:"
					+ journey.getJn_plan());
			break;
		}
	}

	/**
	 * 从数据库获取旅行社行程
	 */
	private Journey Search_Journey_plan() {
		// TODO Auto-generated method stub
		System.out.println("旅行社");
		Connection con = null;
		Journey journey = new Journey();
		try {
			con = t.getConn();
			ResultSet rs = journey_db.Search_Journey_Plan(con);
			while (rs.next()) {
				//				journey = new Journey();
				journey.setJn_name(rs.getString("journey_name"));
				journey.setJn_plan(rs.getString("journey_plan"));
				journey.setJn_money(rs.getString("journey_money"));

				//				planList.add(txtarea);
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			t.closeConn(con);
		}
		return journey;
	}

	/**
	 * 从数据库获取景点行程
	 * @return 
	 */
	private Scene Search_Scene_Plan() {
		// TODO Auto-generated method stub
		Connection con = null;
		Scene scene = new Scene();
		try {
			con = t.getConn();
			ResultSet rs = scene_db.Search_Scene_Plan(con);
			while (rs.next()) {
				//				journey = new Journey();
				scene.setScene_name(rs.getString("Scene_name"));
				scene.setScene_id(rs.getString("Scene_id"));
				scene.setScene_price(rs.getString("Scene_price"));
				txtarea.setText(scene.getScene_name());
				//				planList.add(txtarea);
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			t.closeConn(con);
		}
		return scene;
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PersonInfoFrm().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JComboBox jcbfriend;
	private javax.swing.JComboBox jcbplan;
	private javax.swing.JTextArea txtarea;

	// End of variables declaration//GEN-END:variables

	public void TransUser(User user) {
		// TODO Auto-generated method stub

	}

}