/*
 * Search.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;

import javax.swing.JOptionPane;

import com.DataBase.Journey_db;
import com.DataBase.Scene_db;
import com.DataBase.User_db;
import com.Model.Journey;
import com.Model.Scene;
import com.Model.User;
import com.Util.Tools;

/**
 * 
 * @author __USER__
 */
public class Search extends javax.swing.JInternalFrame {

	/** Creates new form Search */
	public Search() {
		initComponents();
		this.setLocation(150, 50);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel2 = new javax.swing.JLabel();
		txtsearch = new javax.swing.JTextField();
		btnsearchview = new javax.swing.JButton();
		btnsearchjourney = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setClosable(true);
		setIconifiable(true);
		setVisible(true);
		addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				formMouseClicked(evt);
			}
		});

		jLabel2.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\top1.jpg")); // NOI18N
		jLabel2.setIconTextGap(0);

		txtsearch.setFont(new java.awt.Font("宋体", 0, 36));

		btnsearchview.setFont(new java.awt.Font("宋体", 0, 18));
		btnsearchview
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\sear.png")); // NOI18N
		btnsearchview.setText("\u67e5\u8be2\u666f\u70b9");
		btnsearchview.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnsearchviewActionPerformed(evt);
			}
		});

		btnsearchjourney.setFont(new java.awt.Font("宋体", 0, 18));
		btnsearchjourney
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\sear.png")); // NOI18N
		btnsearchjourney.setText("\u67e5\u8be2\u65c5\u884c\u793e");
		btnsearchjourney.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnsearchjourneyActionPerformed(evt);
			}
		});

		jButton1.setFont(new java.awt.Font("宋体", 0, 18));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\sear.png")); // NOI18N
		jButton1.setText("\u67e5\u8be2\u597d\u53cb");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("宋体", 1, 24));
		jLabel1.setForeground(new java.awt.Color(255, 51, 51));
		jLabel1.setText("\u70ed\u95e8\u65c5\u6e38\u666f\u70b9\u63a8\u8350");

		jLabel3.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\fanjingshan.jpg")); // NOI18N
		jLabel3.setText("jLabel3");
		jLabel3.setIconTextGap(0);
		jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel3MouseClicked(evt);
			}
		});

		jLabel4.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\fangzai.jpg")); // NOI18N
		jLabel4.setText("jLabel4");
		jLabel4.setIconTextGap(0);
		jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel4MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(96, 96, 96)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel3,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		323,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		80,
																		Short.MAX_VALUE)
																.addComponent(
																		jLabel4,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		367,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		btnsearchview,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		180,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		105,
																		Short.MAX_VALUE)
																.addComponent(
																		btnsearchjourney,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		197,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(98, 98,
																		98)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		190,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(
														txtsearch,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														770,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(174, 174, 174))
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										1010, Short.MAX_VALUE)
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jLabel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										163,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(27, 27, 27)
								.addComponent(txtsearch,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jButton1,
																		0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		btnsearchjourney,
																		0,
																		0,
																		Short.MAX_VALUE))
												.addComponent(
														btnsearchview,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														41, Short.MAX_VALUE))
								.addGap(35, 35, 35)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(jLabel4, 0, 0,
														Short.MAX_VALUE)
												.addComponent(
														jLabel3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														156, Short.MAX_VALUE))
								.addContainerGap()));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 防灾科技学院的图片单击事件
	 * @param evt
	 */
	private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {
		try {
			Runtime.getRuntime()
					.exec("cmd /c start https://www.baidu.com/s?wd=防灾科技学院");
		} catch (IOException ee) {
			ee.printStackTrace();
		}
	}

	private void formMouseClicked(java.awt.event.MouseEvent evt) {

		this.toFront();// 置于顶层
	}

	/**
	 * 梵净山的图片单击事件
	 * @param evt
	 */
	private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
		/**
		 * 这里是图片单击事件
		 * 先从数据库中查出当前图片对应的景点信息
		 * 然后传到showScene显示图片对应的景点的信息
		 */
//		showScene showscene = new showScene();
//		Scene_db scene_db = new Scene_db();
//		Scene scene = new Scene();
//		Tools t = new Tools();
//		Connection con = t.getConn();
//		try {
//			scene = scene_db.Search_Scene(con, "梵净山");
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		showscene.showScene(scene);
//		showscene.setVisible(true);
		
		try {
			Runtime.getRuntime()
					.exec("cmd /c start https://www.baidu.com/s?wd=梵净山");
		} catch (IOException ee) {
			ee.printStackTrace();
		}
	}

	/**
	 * 我的查找好友功能
	 * 
	 * @param evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String txtsearch = this.txtsearch.getText();
		Tools t = new Tools();
		User user = new User();
		User_db user_db = new User_db();
		Connection con = null;
		if (t.isEmpty(txtsearch)) {
			JOptionPane.showMessageDialog(null, "输入你要查找的用户名");
		} else {
			try {
				con = t.getConn();
				user = user_db.find_User(con, txtsearch);
				if (user != null) {
					showUser showuser = new showUser();
					showuser.getUserInfo(user);
					showuser.setVisible(true);
					showuser.toFront();
				} else {
					JOptionPane.showMessageDialog(null, "没有这个人");
				}
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
				t.closeConn(con);
			}
		}
	}

	/**
	 * 查找旅行社的功能
	 * 
	 * @param evt
	 */
	private void btnsearchjourneyActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String txtsearch = this.txtsearch.getText();
		Tools t = new Tools();
		Journey journey = new Journey();
		Journey_db journey_db = new Journey_db();
		Connection con = null;
		if (t.isEmpty(txtsearch)) {
			JOptionPane.showMessageDialog(null, "输入你要查找的旅行社");
		} else {
			try {
				con = t.getConn();
				journey = journey_db.Find_Journey(con, txtsearch);
				if (journey.getJn_name() != null) {
					showJourney showjourney = new showJourney();
					showjourney.showJourneyInfo(journey);
					showjourney.setVisible(true);
				} else {
					JOptionPane.showMessageDialog(null, "没有这个旅行社");
				}
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
				t.closeConn(con);
			}
		}
	}

	/**
	 * 查找景点的功能
	 * 
	 * @param evt
	 */
	private void btnsearchviewActionPerformed(java.awt.event.ActionEvent evt) {
		String txtsearch = this.txtsearch.getText();
		Tools t = new Tools();
		Scene scene = new Scene();
		Scene_db scene_db = new Scene_db();
		Connection con = null;
		if (t.isEmpty(txtsearch)) {
			JOptionPane.showMessageDialog(null, "输入你要查找的景点");
		} else {
			try {
				con = t.getConn();
				scene = scene_db.Search_Scene(con, txtsearch);
				if (scene.getScene_name() != null) {
					showScene showscene = new showScene();
					showscene.showScene(scene);
					showscene.setVisible(true);

				} else {
					JOptionPane.showMessageDialog(null, "没有这个景点");
				}
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
				t.closeConn(con);
			}
		}

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnsearchjourney;
	private javax.swing.JButton btnsearchview;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JTextField txtsearch;
	// End of variables declaration//GEN-END:variables

}