/*
 * showUser.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.Connection;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.Model.User;
import com.Util.Tools;

/**
 * 
 * @author __USER__
 */
public class showUser extends javax.swing.JFrame {

	/** Creates new form showUser */
	public showUser() {
		initComponents();
		this.setLocation(500, 200);
		//加载图片
		ImageIcon icon = new ImageIcon("images/2.jpg");
		//将图片放入label中
		JLabel label = new JLabel(icon);
		//设置label的大小
		label.setBounds(0, 0, icon.getIconWidth(), icon.getIconHeight());
		//获取窗口的第二层，将label放入
		this.getLayeredPane().add(label, new Integer(Integer.MIN_VALUE));
		//获取frame的顶层容器,并设置为透明
		Container cp;
		cp = this.getContentPane();
		((JPanel) cp).setOpaque(false);
		cp.setLayout(new BorderLayout());
	}

	// public showUser(User user){
	// super();
	// }

	public void getUserInfo(User user) {
		txtid.setText(user.getId());
		jTextField1.setText(user.getName());
		jTextField3.setText(user.getHome());
		jTextField2.setText(user.getSex());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jLabel5 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jTextField2 = new javax.swing.JTextField();
		txtid = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();

		jLabel5.setText("jLabel5");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("宋体", 0, 48));
		jLabel1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\User.png")); // NOI18N
		jLabel1.setText("\u7528\u6237\u8be6\u7ec6\u4fe1\u606f");

		jLabel2.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel2.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\user_.png")); // NOI18N
		jLabel2.setText("\u59d3\u540d\uff1a");

		jTextField1.setEditable(false);

		jLabel3.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel3.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\sex.png")); // NOI18N
		jLabel3.setText("\u6027\u522b\uff1a");

		jLabel4.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel4.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\home.png")); // NOI18N
		jLabel4.setText("\u7c4d\u8d2f\uff1a");

		jTextField3.setEditable(false);

		jButton1.setFont(new java.awt.Font("宋体", 0, 18));
		jButton1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\add.png")); // NOI18N
		jButton1.setText("\u6dfb\u52a0\u4e3a\u597d\u53cb");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextField2.setEditable(false);

		txtid.setEditable(false);

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel6.setText("ID\u7f16\u53f7:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(273,
																		273,
																		273)
																.addComponent(
																		jLabel1))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(176,
																		176,
																		176)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						112,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jLabel3))
																.addGap(37, 37,
																		37)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jTextField3,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						194,
																						Short.MAX_VALUE)
																				.addComponent(
																						jTextField2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						194,
																						Short.MAX_VALUE)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						194,
																						Short.MAX_VALUE))
																.addGap(86, 86,
																		86)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel6)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										txtid,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										104,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addComponent(
																						jButton1))
																.addGap(32, 32,
																		32)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(44, 44, 44)
								.addComponent(jLabel1)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6)
												.addComponent(
														txtid,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(35, 35,
																		35)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jTextField2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(32, 32,
																		32)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jTextField3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(46, 46,
																		46)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		41,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(79, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String name = jTextField1.getText();
		String sex = jTextField2.getText();
		String home = jTextField3.getText();
		String id = txtid.getText();
		// System.out.println(name);
		// System.out.println(sex);
		// System.out.println(home);

		User user = new User();
		user.setId(id);
		user.setName(name);
		user.setSex(sex);
		user.setHome(home);

		Tools t = new Tools();
		Connection con = t.getConn();
		int n = t.add_Friend(con, user);
		if (n > 0) {
			JOptionPane.showMessageDialog(null, "你们已经是好友了，快一起聊天吧！");
		} else {
			JOptionPane.showMessageDialog(null, "添加好友失败！重新来一次");
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new showUser().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField txtid;
	// End of variables declaration//GEN-END:variables

}