/*
 * showJourney.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.Connection;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.DataBase.Credit_db;
import com.DataBase.Journey_db;
import com.Model.Credit;
import com.Model.Journey;
import com.Util.Tools;

/**
 * 
 * @author __USER__
 */
public class showJourney extends javax.swing.JFrame {

	Tools t = new Tools();
	Journey_db journey_db = new Journey_db();
	Journey journey;

	/** Creates new form showJourney */
	public showJourney() {
		initComponents();
		this.setLocation(500, 200);
		//加载图片
		ImageIcon icon = new ImageIcon("images/2.jpg");
		//将图片放入label中
		JLabel label = new JLabel(icon);
		//设置label的大小
		label.setBounds(0, 0, icon.getIconWidth(), icon.getIconHeight());
		//获取窗口的第二层，将label放入
		this.getLayeredPane().add(label, new Integer(Integer.MIN_VALUE));
		//获取frame的顶层容器,并设置为透明
		Container cp;
		cp = this.getContentPane();
		((JPanel) cp).setOpaque(false);
		cp.setLayout(new BorderLayout());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtname = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txtfounddate = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtgrade = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txtplan = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("宋体", 0, 48));
		jLabel1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\Travel128px_.png")); // NOI18N
		jLabel1.setText("\u65c5\u884c\u793e\u8be6\u7ec6\u4fe1\u606f");

		jLabel2.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel2.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\name48px.png")); // NOI18N
		jLabel2.setText("\u540d \u79f0\uff1a");

		txtname.setEditable(false);

		jLabel3.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel3.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\date48px.png")); // NOI18N
		jLabel3.setText("\u6210\u7acb\u65e5\u671f\uff1a");

		txtfounddate.setEditable(false);

		jLabel4.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel4.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\stars48.png")); // NOI18N
		jLabel4.setText("\u63a8\u8350\u6307\u6570\uff1a");

		txtgrade.setEditable(false);
		txtgrade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtgradeActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel5.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\plan48.png")); // NOI18N
		jLabel5.setText("\u51fa\u884c\u8ba1\u5212\uff1a");

		txtplan.setEditable(false);

		jLabel6.setFont(new java.awt.Font("宋体", 0, 18));
		jLabel6.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\thumbsup48.png")); // NOI18N
		jLabel6.setText("\u81ea\u6211\u8bc4\u4ef7\uff1a");

		jTextArea1.setColumns(20);
		jTextArea1.setEditable(false);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\add48px.png")); // NOI18N
		jButton1.setText("\u6dfb\u52a0\u81f3\u6211\u7684\u8ba1\u5212");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(220,
																		220,
																		220)
																.addComponent(
																		jLabel1))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(58, 58,
																		58)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addGroup(
																														javax.swing.GroupLayout.Alignment.LEADING,
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel4)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		txtgrade,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		189,
																																		Short.MAX_VALUE))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel2)
																																.addGap(32,
																																		32,
																																		32)
																																.addComponent(
																																		txtname,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		189,
																																		Short.MAX_VALUE)))
																								.addGap(54,
																										54,
																										54)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														jLabel5)))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel6)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										jScrollPane1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										376,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jButton1,
																						0,
																						0,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtplan,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						199,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtfounddate,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						199,
																						Short.MAX_VALUE))))
								.addGap(127, 127, 127)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(28, 28, 28)
								.addComponent(jLabel1)
								.addGap(30, 30, 30)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														39,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtfounddate,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(36, 36, 36)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														38,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jLabel5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														38,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtplan,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtgrade,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(41, 41,
																		41)
																.addComponent(
																		jLabel6,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		36,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(31, 31,
																		31)
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(52, 52,
																		52)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		44,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(48, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 添加至我的出行计划旅行社篇功能实现
	 * 
	 * @param evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		String name = txtname.getText();
		String plan = txtplan.getText();
		if (t.isEmpty(name)) {
			JOptionPane.showMessageDialog(null, "未知的错误！");
		} else {
			// 连接数据库，把该旅行社的出行费用查出来
			Connection con = null;
			// try{
			Journey jour = new Journey();
			con = t.getConn();
			jour = journey_db.Find_Journey(con, name);

			if (t.isEmpty(plan)) {
				JOptionPane.showMessageDialog(null, "该旅行社近期没有出行计划!");
			} else {
				System.out.println("lalal");
				int n1 = JOptionPane.showConfirmDialog(null,
						"将要扣除" + jour.getJn_money() + "元出行费用,是否继续？");
				if (n1 == 0) {
					try {
						// 实现数据库对银行卡的扣钱操作
						Credit_db credit_db = new Credit_db();
						int n = credit_db.KouQian(con, jour.getJn_money());
						if (n > 0) {
							JOptionPane.showMessageDialog(null, "扣钱成功");
							con = t.getConn();
							journey = new Journey();
							journey.setJn_name(name);
							journey.setJn_plan(plan);
							journey.setJn_money(jour.getJn_money());
							int n11 = journey_db.add_Journey(con, journey);
							if (n11 > 0) {
								JOptionPane.showMessageDialog(null,
										"添加成功!请前往个人信息查看我的行程");
							} else {
								JOptionPane
										.showMessageDialog(null, "添加失败!再试一次");
							}

						} else {
							JOptionPane.showMessageDialog(null, "扣钱失败");
						}
					} catch (Exception e) {
						e.printStackTrace();
					} finally {
						t.closeConn(con);
					}

				} else {

				}
			}
		}
	}

	/**
	 * 将Search界面选中的旅行社信息显示到这个界面上
	 * 
	 * @param journey
	 */
	public void showJourneyInfo(Journey journey) {
		txtname.setText(journey.getJn_name());
		txtfounddate.setText(journey.getJn_year());
		txtgrade.setText(journey.getJn_grade());
		txtplan.setText(journey.getJn_plan());
		jTextArea1.setText(journey.getJn_details());

	}

	private void txtgradeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new showJourney().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField txtfounddate;
	private javax.swing.JTextField txtgrade;
	private javax.swing.JTextField txtname;
	private javax.swing.JTextField txtplan;
	// End of variables declaration//GEN-END:variables

}