/*
 * showScene.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.sql.Connection;

import javax.swing.JOptionPane;

import com.DataBase.Credit_db;
import com.DataBase.Scene_db;
import com.Model.Scene;
import com.Util.Tools;

/**
 * 
 * @author __USER__
 */
public class showScene extends javax.swing.JFrame {

	/** Creates new form showScene */
	public showScene() {
		initComponents();
		this.setLocation(500, 200);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtscene_name = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		txtscene_price = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtscene_grade = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txtscene_local = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtscene_details = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		tx = new javax.swing.JLabel();
		txtid = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 48));
		jLabel1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\tourbus128px.png")); // NOI18N
		jLabel1.setText("\u666f\u70b9\u8be6\u60c5");
		jLabel1.setIconTextGap(50);

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel2.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\scene_name48px.png")); // NOI18N
		jLabel2.setText("\u540d\u79f0\uff1a");

		txtscene_name.setEditable(false);

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel3.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\money_48px.png")); // NOI18N
		jLabel3.setText("\u95e8\u7968:");

		txtscene_price.setEditable(false);

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel4.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\stars48.png")); // NOI18N
		jLabel4.setText("\u63a8\u8350\u7b49\u7ea7:");

		txtscene_grade.setEditable(false);

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel5.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\great_wall_48px.png")); // NOI18N
		jLabel5.setText("\u7701\u4efd:");

		txtscene_local.setEditable(false);

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel6.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\thumbsup48.png")); // NOI18N
		jLabel6.setText("\u8be6\u60c5:");

		txtscene_details.setColumns(20);
		txtscene_details.setEditable(false);
		txtscene_details.setRows(5);
		jScrollPane1.setViewportView(txtscene_details);

		jButton1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\add.png")); // NOI18N
		jButton1.setText("\u6dfb\u52a0\u81f3\u6211\u7684\u884c\u7a0b");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		tx.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		tx.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\numbered_48pa.png")); // NOI18N
		tx.setText("\u666f\u533a\u7f16\u53f7\uff1a");

		txtid.setEditable(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel6)
																.addContainerGap())
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(
																						jLabel4)
																				.addContainerGap())
																.addGroup(
																		layout.createSequentialGroup()
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addGroup(
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										layout.createSequentialGroup()
																												.addComponent(
																														tx)
																												.addPreferredGap(
																														javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																																.addComponent(
																																		jLabel1,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		451,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addGroup(
																																		layout.createSequentialGroup()
																																				.addGroup(
																																						layout.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING,
																																								false)
																																								.addComponent(
																																										txtscene_name,
																																										javax.swing.GroupLayout.Alignment.LEADING)
																																								.addComponent(
																																										txtid,
																																										javax.swing.GroupLayout.Alignment.LEADING,
																																										javax.swing.GroupLayout.DEFAULT_SIZE,
																																										124,
																																										Short.MAX_VALUE)
																																								.addComponent(
																																										txtscene_grade,
																																										javax.swing.GroupLayout.DEFAULT_SIZE,
																																										113,
																																										Short.MAX_VALUE))
																																				.addGap(186,
																																						186,
																																						186)
																																				.addComponent(
																																						txtscene_local,
																																						javax.swing.GroupLayout.DEFAULT_SIZE,
																																						141,
																																						Short.MAX_VALUE))
																																.addComponent(
																																		jScrollPane1,
																																		javax.swing.GroupLayout.DEFAULT_SIZE,
																																		451,
																																		Short.MAX_VALUE)))
																								.addGroup(
																										layout.createSequentialGroup()
																												.addComponent(
																														jLabel2)
																												.addGap(234,
																														234,
																														234)
																												.addGroup(
																														layout.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																																.addComponent(
																																		jButton1)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						jLabel5)
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addComponent(
																																										jLabel3)
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																										40,
																																										Short.MAX_VALUE)
																																								.addComponent(
																																										txtscene_price,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										141,
																																										javax.swing.GroupLayout.PREFERRED_SIZE))))))
																				.addGap(271,
																						271,
																						271))))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		120,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(177,
																		177,
																		177)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						tx,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						48,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						txtid,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						37,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						txtscene_local,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						35,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addGap(28, 28, 28)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														txtscene_price,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														37,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2)
												.addComponent(
														txtscene_name,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														35,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(16, 16, 16)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														txtscene_grade,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														38,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														43,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(27, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/*
	 * 添加景点到我的行程篇功能实现
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		Tools t = new Tools();
		Scene_db scene_db = new Scene_db();
		String scene_id = txtid.getText();
		String scene_name = txtscene_name.getText();
		Scene scene = new Scene();
		Connection con = null;
		try {
			con = t.getConn();
			scene = scene_db.Search_Scene(con, scene_name);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			t.closeConn(con);
		}

		if (t.isNotEmpty(scene_id)) {
			// if (t.isEmpty(scene_id)) {
			// JOptionPane.showMessageDialog(null, "未知的错误!");
			// } else {
			int n1 = JOptionPane.showConfirmDialog(null,
					"即将从银行卡扣除" + scene.getScene_price() + "门票钱,是否继续？");
			if (n1 == 0) {
				try {
					con = t.getConn();
					int n = scene_db.add_Scene(con, scene_id, scene_name);
					Credit_db credit_db = new Credit_db();
					int n11 = credit_db.KouQian(con, scene.getScene_price());
					if (n11 > 0) {
						JOptionPane.showMessageDialog(null, "扣钱成功,祝您旅行愉快");
						if (n > 0) {
							JOptionPane.showMessageDialog(null,
									"添加成功!请前往个人信息查看我的行程");
						} else {
							JOptionPane.showMessageDialog(null, "添加失败!再试一次");
						}
					} else {
						JOptionPane.showMessageDialog(null, "扣钱失败,稍后再试");
					}
				} catch (Exception e) {
					e.printStackTrace();
				} finally {
					t.closeConn(con);
				}
			} else {

			}
		} else {
			JOptionPane.showMessageDialog(null, "未知的错误");
		}
	}

	/**
	 * 显示传过来的景点信息
	 * 
	 * @param scene
	 */
	public void showScene(Scene scene) {
		this.txtid.setText(scene.getScene_id());
		this.txtscene_details.setText(scene.getScene_details());
		this.txtscene_grade.setText(scene.getScene_grade());
		this.txtscene_local.setText(scene.getScene_local());
		this.txtscene_name.setText(scene.getScene_name());
		this.txtscene_price.setText(scene.getScene_price());
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new showScene().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel tx;
	private javax.swing.JTextField txtid;
	private javax.swing.JTextArea txtscene_details;
	private javax.swing.JTextField txtscene_grade;
	private javax.swing.JTextField txtscene_local;
	private javax.swing.JTextField txtscene_name;
	private javax.swing.JTextField txtscene_price;
	// End of variables declaration//GEN-END:variables

}