/*
 * UserinfoManageFrm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.View;

import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import com.DataBase.Journey_db;
import com.DataBase.User_db;
import com.Model.Journey;
import com.Model.User;
import com.Util.Tools;

/**
 * 
 * @author __USER__
 */
public class UserinfoManageFrm extends javax.swing.JInternalFrame {

	/** Creates new form UserinfoManageFrm */
	public UserinfoManageFrm() {
		initComponents();
		this.setLocation(150, 50);
		this.filltableUserinfoFrm(new User());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		txtsearch = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txtname = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txthome = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		txtid = new javax.swing.JTextField();
		btnUpdate = new javax.swing.JButton();
		btnDel = new javax.swing.JButton();
		jrbman = new javax.swing.JRadioButton();
		jrbfamale = new javax.swing.JRadioButton();

		setClosable(true);
		setIconifiable(true);

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "姓名", "性别", "籍贯", "学号" }) {
			boolean[] canEdit = new boolean[] { false, false, false, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 568,
								Short.MAX_VALUE).addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 208,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jButton1.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\sear.png")); // NOI18N
		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setText("\u59d3\u540d\uff1a");

		jLabel2.setText("\u6027\u522b\uff1a");

		jLabel3.setText("\u7c4d\u8d2f\uff1a");

		jLabel4.setText("\u5b66\u53f7\uff1a");

		txtid.setEditable(false);

		btnUpdate
				.setIcon(new javax.swing.ImageIcon(
						"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\26154.png")); // NOI18N
		btnUpdate.setText("\u4fee\u6539");
		btnUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUpdateActionPerformed(evt);
			}
		});

		btnDel.setIcon(new javax.swing.ImageIcon(
				"E:\\我爱学习\\jps\\workspace\\Java_System_Moran\\images\\error_2.png")); // NOI18N
		btnDel.setText("\u5220\u9664");
		btnDel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDelActionPerformed(evt);
			}
		});

		buttonGroup1.add(jrbman);
		jrbman.setSelected(true);
		jrbman.setText("\u7537");

		buttonGroup1.add(jrbfamale);
		jrbfamale.setText("\u5973");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(41, 41, 41)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				txtname,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				107,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								btnUpdate,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								107,
																								Short.MAX_VALUE)
																						.addComponent(
																								txthome))))
										.addGap(74, 74, 74)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jrbman)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				20,
																				Short.MAX_VALUE)
																		.addComponent(
																				jrbfamale))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanel2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								btnDel,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								106,
																								Short.MAX_VALUE)
																						.addComponent(
																								txtid,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								106,
																								Short.MAX_VALUE))))
										.addContainerGap(144, Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(43, 43, 43)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																txtname,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(jrbfamale)
														.addComponent(jrbman))
										.addGap(34, 34, 34)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																txthome,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addComponent(
																txtid,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(47, 47, 47)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(btnUpdate)
														.addComponent(btnDel))
										.addGap(26, 26, 26)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(210,
																		210,
																		210)
																.addComponent(
																		txtsearch,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		400,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(37, 37,
																		37)
																.addComponent(
																		jButton1))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(180,
																		180,
																		180)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addComponent(
																						jPanel2,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jPanel1,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addContainerGap(199, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(74, 74, 74)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(jButton1, 0, 0,
														Short.MAX_VALUE)
												.addComponent(
														txtsearch,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														35, Short.MAX_VALUE))
								.addGap(31, 31, 31)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(27, 27, 27)
								.addComponent(jPanel2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										231,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(61, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * 修改用户信息
	 * @param evt
	 */
	private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {

		String User_name = this.txtname.getText();
//		String User_sex = this.txtsex.getText();
		String User_home = this.txthome.getText();
		String User_id = this.txtid.getText();

		User user = new User();
		user.setName(User_name);
		user.setHome(User_home);
		user.setId(User_id);
		String sex="";
		if(jrbfamale.isSelected()){
			sex="女";
		}else{
			sex="男";
		}
		user.setSex(sex);
		Connection con = null;
		User_db user_db = new User_db();
		Tools t = new Tools();
		if (t.isEmpty(User_name)) {
			JOptionPane.showMessageDialog(null, "请选择你要修改的旅行社");
		} else {
			try {
				con = t.getConn();
				int n = user_db.Update_User(con, user);
				if (n > 0) {
					JOptionPane.showMessageDialog(null, "修改成功！");
					resetValue();
					filltableUserinfoFrm(new User());

				} else {
					JOptionPane.showMessageDialog(null, "修改失败！");
				}
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
				t.closeConn(con);
			}
		}

	}

	/**
	 * 删除用户
	 */
	private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {

		String user_id = this.txtid.getText();
		Tools t = new Tools();
		User_db user_db = new User_db();
		if (t.isEmpty(user_id)) {
			JOptionPane.showMessageDialog(null, "请选择你要删除的用户");
		} else {
			Connection con = t.getConn();
			int n = user_db.Del_User(con, user_id);
			if (n > 0) {
				JOptionPane.showMessageDialog(null, "删除成功!");
				resetValue();
				filltableUserinfoFrm(new User());
			} else {
				JOptionPane.showMessageDialog(null, "删除失败！");
			}

		}

	}

	/**
	 * 鼠标选中行事件处理
	 * @param evt
	 */
	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {

		int row = jTable1.getSelectedRow();
		txtname.setText((String) jTable1.getValueAt(row, 0));
		txthome.setText((String) jTable1.getValueAt(row, 2));
		txtid.setText((String) jTable1.getValueAt(row, 3));
		//		txtsex.setText((String) jTable1.getValueAt(row, 1));
		//把性别通过单选按钮显示出来
		if (jTable1.getValueAt(row, 1).equals("男")) {
			jrbman.setSelected(true);
		} else {
			jrbfamale.setSelected(true);
		}

	}

	/**
	 * 查询事件处理
	 * 
	 * @param evt
	 */
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		String User_name = this.txtsearch.getText();
		Tools t = new Tools();
		//		if (t.isEmpty(User_name)) {
		//			JOptionPane.showMessageDialog(null, "请输入你要查找的用户名");
		//		} else {
		User user = new User();
		user.setName(User_name);
		this.filltableUserinfoFrm(user);
		//		}

	}

	/**
	 * 初始化显示用户的table
	 * 
	 * @param user
	 */
	public void filltableUserinfoFrm(User user) {

		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.setRowCount(0);// 清空表格
		Connection con = null;
		Tools t = new Tools();
		try {
			con = t.getConn();
			User_db user_db = new User_db();
			ResultSet rs = user_db.list(con, user);

			//				System.out.println("能进来吗userinfomanagefrm426");
			while (rs.next()) {
				//					System.out.println("能进来吗userinfomanagefrm428");
				// System.out.println("filltable裏面的這裏呢");
				Vector v = new Vector();
				v.add(rs.getString("name"));
				//				System.out.println(rs.getString("name"));
				v.add(rs.getString("sex"));
				v.add(rs.getString("home"));
				v.add(rs.getString("id"));
				dtm.addRow(v);
				//					System.out.println("fill table裏面的這裏呢");
			}
			//				if (!rs.next()) {
			//					JOptionPane.showMessageDialog(null, "没有这个人");
			//					JOptionPane.showMessageDialog(null, "你找到了我解决不了的系统Bug,来我这里上班吧");
			//				}

		} catch (Exception e) {
			e.printStackTrace();

		} finally {
			t.closeConn(con);
		}

	}

	/**
	 * 清空文本框
	 */
	public void resetValue() {
		txtname.setText("");
		txtid.setText("");
//		txtsex.setText("");
		jrbman.setSelected(true);
		txthome.setText("");

	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton btnDel;
	private javax.swing.JButton btnUpdate;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JRadioButton jrbfamale;
	private javax.swing.JRadioButton jrbman;
	private javax.swing.JTextField txthome;
	private javax.swing.JTextField txtid;
	private javax.swing.JTextField txtname;
	private javax.swing.JTextField txtsearch;
	// End of variables declaration//GEN-END:variables

}